"use strict";

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("Pets", [
      {
        name: "Morton",
        age: 2,
        weight: 14,
        gender: "Male",
        breed: "dog",
        storeId: 1,
        ownerId: 1,
        hasShots: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Reynard",
        age: 8,
        weight: 22,
        gender: "Male",
        breed: "cat",
        storeId: 3,
        ownerId: null,
        hasShots: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sidoney",
        age: 7,
        weight: 39,
        gender: "Female",
        breed: "bird",
        storeId: 1,
        ownerId: 13,
        hasShots: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Tyrone",
        age: 2,
        weight: 22,
        gender: "Male",
        breed: "snake",
        storeId: 3,
        ownerId: 15,
        hasShots: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Grenville",
        age: 2,
        weight: 36,
        gender: "Male",
        breed: "dog",
        storeId: 3,
        ownerId: null,
        hasShots: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Waverley",
        age: 4,
        weight: 20,
        gender: "Male",
        breed: "cat",
        storeId: 1,
        ownerId: 7,
        hasShots: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Brendis",
        age: 10,
        weight: 40,
        gender: "Male",
        breed: "tutle",
        storeId: 3,
        ownerId: null,
        hasShots: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Carling",
        age: 1,
        weight: 17,
        gender: "Male",
        breed: "bird",
        storeId: 1,
        ownerId: 12,
        hasShots: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Ikey",
        age: 9,
        weight: 14,
        gender: "Male",
        breed: "dog",
        storeId: 2,
        ownerId: null,
        hasShots: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Linell",
        age: 3,
        weight: 47,
        gender: "Female",
        breed: "cat",
        storeId: 3,
        ownerId: 9,
        hasShots: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Nikaniki",
        age: 5,
        weight: 12,
        gender: "Female",
        breed: "snake",
        storeId: 2,
        ownerId: 14,
        hasShots: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sayre",
        age: 5,
        weight: 38,
        gender: "Female",
        breed: "bird",
        storeId: 3,
        ownerId: 2,
        hasShots: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Kamilah",
        age: 6,
        weight: 8,
        gender: "Female",
        breed: "dog",
        storeId: 2,
        ownerId: 10,
        hasShots: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Sonni",
        age: 6,
        weight: 33,
        gender: "Female",
        breed: "cat",
        storeId: 3,
        ownerId: 11,
        hasShots: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Alana",
        age: 1,
        weight: 29,
        gender: "Female",
        breed: "turtle",
        storeId: 1,
        ownerId: 5,
        hasShots: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Keri",
        age: 8,
        weight: 37,
        gender: "Female",
        breed: "cat",
        storeId: 2,
        ownerId: 8,
        hasShots: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Doti",
        age: 4,
        weight: 42,
        gender: "Female",
        breed: "dog",
        storeId: 1,
        ownerId: 4,
        hasShots: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Paxon",
        age: 9,
        weight: 6,
        gender: "Male",
        breed: "cat",
        storeId: 1,
        ownerId: null,
        hasShots: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Oswald",
        age: 5,
        weight: 19,
        gender: "Male",
        breed: "bird",
        storeId: 1,
        ownerId: 6,
        hasShots: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Wallace",
        age: 8,
        weight: 24,
        gender: "Male",
        breed: "dog",
        storeId: 1,
        ownerId: 3,
        hasShots: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Pets", null, {});
  },
};
